<a href="https://colab.research.google.com/github/diapatel/DSMP-content/blob/main/Copy_of_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CREATING NUMPY ARRAYS

In [ ]:
import numpy as np

#1-d array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2-d array
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3-d array
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# creating numpy arrays with a specific data type
d = np.array([1,2,3], dtype=float)
print(d)

# creating array of bool type
e = np.array([1,2,3], dtype=bool)
print(e)

[1. 2. 3.]
[ True  True  True]


In [ ]:
# np.arange() - creates a numpy array with numbers within a given range
f = np.arange(1,9,2)
print(f)

[1 3 5 7]


In [ ]:
# np.reshape() -  reshapes a numpy array to a given number of rows and cols if possible
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# np.ones() and np.zeros()
print(np.zeros((3,2)))
print(np.ones((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# np.random() - generates a numpy array with random numbers between 0 and 1
np.random.random((3,2))

array([[0.92509651, 0.37604784],
       [0.36263789, 0.12269943],
       [0.60512684, 0.50772721]])

In [ ]:
# np.lisnpace() - creates an array within the given range with equidistant numbers
np.linspace(-10,10,10) # generates an array with 10 equidistant numbers between -10 and 10

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity() - creates an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# ARRAY ATTRIBUTES


In [ ]:
# creating some demo arrays
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
# ndim - returns the dimensions of the array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
# shape - returns shape of the array
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
# size - returns number of elemetns in the array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
# itemsize - returns the size occupied by each item of the array in the memory
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [ ]:
# dtype - returns the datatype of the array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing datatype of an array

In [ ]:
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

# ARRAY OPERATIONS

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
#  SCALAR OPERATIONS
print("a1+a2", a1+a2)
print("-------------------------------")
print("a1-a2", a1-a2)
print("-------------------------------")
print("a1*a2", a1*a2)
print("-------------------------------")
print("a1**2", a1**2)

a1+a2 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
-------------------------------
a1-a2 [[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
-------------------------------
a1*a2 [[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
-------------------------------
a1**2 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [ ]:
# RELATIONAL OPERATORS
print("a1>a2", a1>a2)

a1>a2 [[False False False False]
 [False False False False]
 [False False False False]]


In [ ]:
!git config --global user.email "pateldiya703@gmail.com"
!git config --global user.name "Diya Patel"

In [ ]:
!git clone https://github.com/diapatel/DSMP-content.git
%cd DSMP-content


Cloning into 'DSMP-content'...
/content/DSMP-content


In [ ]:
!mv "/content/NumPy.ipynb" .


mv: cannot stat '/content/NumPy.ipynb': No such file or directory


In [ ]:
pwd

'/content/DSMP-content'

In [ ]:

!git clone https://github.com/diapatel/DSMP-content.git



Cloning into 'DSMP-content'...


In [ ]:
%cd DSMP-content


/content/DSMP-content/DSMP-content


In [ ]:
!cp "/content/NumPy.ipynb" .


cp: cannot stat '/content/NumPy.ipynb': No such file or directory


In [ ]:
!ls /content

DSMP-content  sample_data
